In [48]:
import numpy as np


# Soal 1

In [19]:

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Soal 2

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

## Soal 3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## Soal 4

In [44]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])